export default {
  icDropDown: require('../components/Images/baseline_arrow_drop_down_white_18.png'),
  icDashboard: require('../components/Images/baseline_dashboard_white_18.png'),
  icList: require('../components/Images/baseline_format_list_bulleted_white_18.png'),
  productImage: require('../components/Images/productImage.png'),
  star: require('../components/Images/baseline_star_white_18.png'),
  unfavorited: require('../components/Images/baseline_favorite_border_white_18.png'),
  bannerlelang: require('../components/Images/Banner_Lelang.png'),
  produklelang: require('../components/Images/produklelang.png'),
  produklelang2: require('../components/Images/produklelang2.png'),
  produklelang3: require('../components/Images/produklelang3.png'),
  produklelang5: require('../components/Images/produklelang5.png'),
  produklelang6: require('../components/Images/produklelang6.png'),
  popUpSabyan: require('../components/Images/sabyan_popup.png'),
  popUpTribes: require('../components/Images/image-popup.png'),
  logolelanghome: require('../components/Images/logolelanghome.png'),
  imageBanner1: require('../components/Images/image-banner1.png'),
  imageBanner2: require('../components/Images/image-banner2.png'),
  iconOnBoard1: require('../components/Images/icon-onboard1.png'),
  iconOnBoard2: require('../components/Images/icon-onboard2.png'),
  iconOnBoard3: require('../components/Images/icon-onboard3.png'),
  icClose: require('../components/Images/ic_close.png'),
};
